# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='motorspeedleft',
            new_name='task_direction',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='motorspeedright',
            new_name='task_number',
        ),
        migrations.AddField(
            model_name='robot',
            name='task_speed',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robot',
            name='task_time',
            field=models.FloatField(blank=True, default=datetime.datetime(2016, 4, 4, 20, 46, 26, 288181, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
